/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    services: Service;
    'reception-formats': ReceptionFormat;
    'menu-categories': MenuCategory;
    'menu-items': MenuItem;
    'signature-menus': SignatureMenu;
    'fresh-products': FreshProduct;
    events: Event;
    references: Reference;
    testimonials: Testimonial;
    gallery: Gallery;
    'journal-posts': JournalPost;
    redirects: Redirect;
    leads: Lead;
    'experience-interest': ExperienceInterest;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'reception-formats': ReceptionFormatsSelect<false> | ReceptionFormatsSelect<true>;
    'menu-categories': MenuCategoriesSelect<false> | MenuCategoriesSelect<true>;
    'menu-items': MenuItemsSelect<false> | MenuItemsSelect<true>;
    'signature-menus': SignatureMenusSelect<false> | SignatureMenusSelect<true>;
    'fresh-products': FreshProductsSelect<false> | FreshProductsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    references: ReferencesSelect<false> | ReferencesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    'journal-posts': JournalPostsSelect<false> | JournalPostsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'experience-interest': ExperienceInterestSelect<false> | ExperienceInterestSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fr') | ('en' | 'fr')[];
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
    'home-page': HomePage;
    'entry-screen': EntryScreen;
    'contact-settings': ContactSetting;
    'seo-settings': SeoSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'entry-screen': EntryScreenSelect<false> | EntryScreenSelect<true>;
    'contact-settings': ContactSettingsSelect<false> | ContactSettingsSelect<true>;
    'seo-settings': SeoSettingsSelect<false> | SeoSettingsSelect<true>;
  };
  locale: 'en' | 'fr';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Private CMS accounts. Editors cannot manage users or roles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Approved image library with accessible metadata and responsive derivatives.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image purpose and visible content; do not begin with “image of”.
   */
  alt: string;
  caption?: string | null;
  category:
    | 'food'
    | 'cocktail'
    | 'buffet'
    | 'table-service'
    | 'mama-emma-fresh'
    | 'events'
    | 'team'
    | 'brand'
    | 'experience'
    | 'behind-the-scenes'
    | 'corporate'
    | 'institutional'
    | 'celebrations';
  /**
   * Photographer/source credit and rights note when required.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Controlled editorial pages; blocks cannot introduce arbitrary HTML or styling.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  seedKey?: string | null;
  title: string;
  /**
   * URL segment. Lowercase letters, numbers, and hyphens only; changes may create redirects.
   */
  slug: string;
  pageKind: 'about' | 'contact' | 'editorial' | 'experience' | 'fresh' | 'gallery' | 'local-seo' | 'menus' | 'services';
  /**
   * Leave empty to keep the wording currently published on the site.
   */
  editorial?: {
    intro?: {
      /**
       * The small label above the page title.
       */
      eyebrow?: string | null;
      /**
       * Section headings are set in two parts: the lead is typographically neutral, the accent is the emphasised half. Fill both or neither.
       */
      headingLead?: string | null;
      headingAccent?: string | null;
      /**
       * One or two sentences under the title.
       */
      lede?: string | null;
    };
    closing?: {
      heading?: string | null;
      body?: string | null;
      action?: {
        label?: string | null;
        /**
         * Where the button leads. The localized URL is resolved by the site.
         */
        route?: ('about' | 'contact' | 'gallery' | 'fresh' | 'menus' | 'quote' | 'services' | 'experience') | null;
      };
    };
  };
  /**
   * Leave empty to keep the wording currently published on the site. Chapters are replaced as a set: publish all of them or none.
   */
  aboutStory?: {
    /**
     * The portrait beside the opening. Until one is uploaded the page shows a labelled placeholder naming the shoot that is missing — it never invents an image.
     */
    introImage?: (number | null) | Media;
    eyebrow?: string | null;
    /**
     * Section headings are set in two parts: the lead is typographically neutral, the accent is the emphasised half. Fill both or neither.
     */
    heading?: string | null;
    headingAccent?: string | null;
    /**
     * A chapter needs a title and at least one paragraph to count. Incomplete rows are ignored rather than published half-empty.
     */
    chapters?:
      | {
          /**
           * The short marker in the margin, e.g. a place or a period.
           */
          label?: string | null;
          title?: string | null;
          /**
           * One row per paragraph.
           */
          body?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          /**
           * Optional. Rendered as a list under the paragraphs.
           */
          list?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    pullQuote?: {
      text?: string | null;
      attribution?: string | null;
    };
  };
  /**
   * Leave empty to keep the wording currently published on the site. The contact details themselves live in Site → Contact settings.
   */
  contactChannels?: {
    eyebrow?: string | null;
    heading?: string | null;
  };
  layout?:
    | (
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            subline?: string | null;
            image: number | Media;
            alignment: 'left' | 'center';
            action?: {
              label?: string | null;
              route?:
                | ('about' | 'contact' | 'experience' | 'fresh' | 'gallery' | 'home' | 'menus' | 'quote' | 'services')
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            image: number | Media;
            imageSide: 'left' | 'right';
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            action?: {
              label?: string | null;
              route?:
                | ('about' | 'contact' | 'experience' | 'fresh' | 'gallery' | 'home' | 'menus' | 'quote' | 'services')
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'editorialTextImage';
          }
        | {
            image: number | Media;
            caption?: string | null;
            height: 'cinematic' | 'viewport' | 'compact';
            id?: string | null;
            blockName?: string | null;
            blockType: 'fullBleedImage';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            statements: {
              statement: string;
              id?: string | null;
            }[];
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            id?: string | null;
            blockName?: string | null;
            blockType: 'manifesto';
          }
        | {
            quote: string;
            attribution?: string | null;
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            items?: (number | Service)[] | null;
            layout: 'editorial' | 'immersive' | 'compact';
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            action?: {
              label?: string | null;
              route?:
                | ('about' | 'contact' | 'experience' | 'fresh' | 'gallery' | 'home' | 'menus' | 'quote' | 'services')
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'serviceShowcase';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            items?: (number | SignatureMenu)[] | null;
            layout: 'editorial' | 'immersive' | 'compact';
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            action?: {
              label?: string | null;
              route?:
                | ('about' | 'contact' | 'experience' | 'fresh' | 'gallery' | 'home' | 'menus' | 'quote' | 'services')
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'menuShowcase';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            items?: (number | MenuItem)[] | null;
            layout: 'editorial' | 'immersive' | 'compact';
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            action?: {
              label?: string | null;
              route?:
                | ('about' | 'contact' | 'experience' | 'fresh' | 'gallery' | 'home' | 'menus' | 'quote' | 'services')
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'signatureDishes';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            items?: (number | FreshProduct)[] | null;
            layout: 'editorial' | 'immersive' | 'compact';
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            action?: {
              label?: string | null;
              route?:
                | ('about' | 'contact' | 'experience' | 'fresh' | 'gallery' | 'home' | 'menus' | 'quote' | 'services')
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'freshProducts';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            items?: (number | Gallery)[] | null;
            layout: 'editorial-grid' | 'filmstrip';
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            id?: string | null;
            blockName?: string | null;
            blockType: 'galleryPreview';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            references?: (number | Reference)[] | null;
            presentation: 'editorial' | 'quiet-list';
            id?: string | null;
            blockName?: string | null;
            blockType: 'references';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            steps: {
              title: string;
              description?: string | null;
              id?: string | null;
            }[];
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            id?: string | null;
            blockName?: string | null;
            blockType: 'process';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            description: string;
            disclaimer: string;
            image?: (number | null) | Media;
            action?: {
              label?: string | null;
              route?:
                | ('about' | 'contact' | 'experience' | 'fresh' | 'gallery' | 'home' | 'menus' | 'quote' | 'services')
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'mamaEmmaExperienceTeaser';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            action?: {
              label?: string | null;
              route?:
                | ('about' | 'contact' | 'experience' | 'fresh' | 'gallery' | 'home' | 'menus' | 'quote' | 'services')
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            left: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            right: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            id?: string | null;
            blockName?: string | null;
            blockType: 'editorialSplit';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            chapterKey: 'congo' | 'maya-maya' | 'senegal' | 'professional-hospitality' | 'ghana' | 'meste-today';
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            image?: (number | null) | Media;
            layout: 'image-left' | 'image-right' | 'text-only';
            id?: string | null;
            blockName?: string | null;
            blockType: 'storyChapter';
          }
      )[]
    | null;
  /**
   * A locale is public only after its copy and required media have been reviewed. Publishing alone is not sufficient.
   */
  localeReadiness?: {
    en?: boolean | null;
    fr?: boolean | null;
  };
  /**
   * Optional search and sharing overrides. Empty fields use approved site defaults.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * MESTE service worlds and their approved supporting content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  seedKey?: string | null;
  title: string;
  /**
   * URL segment. Lowercase letters, numbers, and hyphens only; changes may create redirects.
   */
  slug: string;
  category: 'celebrations' | 'corporate' | 'institutional-diplomatic' | 'bespoke';
  positioning: string;
  story?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  formats?: (number | ReceptionFormat)[] | null;
  menus?: (number | SignatureMenu)[] | null;
  gallery?: (number | Gallery)[] | null;
  references?: (number | Reference)[] | null;
  cta?: {
    label?: string | null;
    route?: ('about' | 'contact' | 'experience' | 'fresh' | 'gallery' | 'home' | 'menus' | 'quote' | 'services') | null;
  };
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * A locale is public only after its copy and required media have been reviewed. Publishing alone is not sufficient.
   */
  localeReadiness?: {
    en?: boolean | null;
    fr?: boolean | null;
  };
  /**
   * Optional search and sharing overrides. Empty fields use approved site defaults.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Service formats. Guest ranges remain empty until verified.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reception-formats".
 */
export interface ReceptionFormat {
  id: number;
  seedKey?: string | null;
  name: string;
  /**
   * URL segment. Lowercase letters, numbers, and hyphens only; changes may create redirects.
   */
  slug: string;
  description: string;
  recommendedEventTypes?:
    | {
        eventType: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Enter only a range confirmed by MESTE.
   */
  verifiedGuestRange?: {
    minimum?: number | null;
    maximum?: number | null;
  };
  gallery?: (number | Gallery)[] | null;
  relatedMenus?: (number | SignatureMenu)[] | null;
  cta?: {
    label?: string | null;
    route?: ('about' | 'contact' | 'experience' | 'fresh' | 'gallery' | 'home' | 'menus' | 'quote' | 'services') | null;
  };
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * A locale is public only after its copy and required media have been reviewed. Publishing alone is not sufficient.
   */
  localeReadiness?: {
    en?: boolean | null;
    fr?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Curated gallery entries with localized accessibility and editorial metadata.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  image: number | Media;
  alt: string;
  caption?: string | null;
  category:
    | 'food'
    | 'cocktail'
    | 'buffet'
    | 'table-service'
    | 'mama-emma-fresh'
    | 'events'
    | 'team'
    | 'brand'
    | 'experience'
    | 'behind-the-scenes'
    | 'corporate'
    | 'institutional'
    | 'celebrations';
  event?: (number | null) | Event;
  service?: (number | null) | Service;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * A locale is public only after its copy and required media have been reviewed. Publishing alone is not sufficient.
   */
  localeReadiness?: {
    en?: boolean | null;
    fr?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Event architecture for future real editions. Do not invent dates, venues, capacity, or price.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  seedKey?: string | null;
  title: string;
  /**
   * URL segment. Lowercase letters, numbers, and hyphens only; changes may create redirects.
   */
  slug: string;
  eventStatus: 'concept' | 'coming-soon' | 'registration-open' | 'sold-out' | 'completed';
  theme?: string | null;
  shortDescription?: string | null;
  story?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Leave empty for concept-only entries.
   */
  schedule?: {
    date?: string | null;
    venue?: string | null;
    capacity?: number | null;
    price?: number | null;
    currency?: ('GHS' | 'USD' | 'EUR') | null;
  };
  menu?: (number | null) | SignatureMenu;
  entertainment?: string | null;
  dressCode?: string | null;
  featuredImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  registration: {
    mode: 'interest-only' | 'external-link' | 'internal-registration';
    externalURL?: string | null;
  };
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * A locale is public only after its copy and required media have been reviewed. Publishing alone is not sufficient.
   */
  localeReadiness?: {
    en?: boolean | null;
    fr?: boolean | null;
  };
  /**
   * Optional search and sharing overrides. Empty fields use approved site defaults.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Curated menu narratives and course groupings. Pricing is intentionally absent.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signature-menus".
 */
export interface SignatureMenu {
  id: number;
  seedKey?: string | null;
  title: string;
  /**
   * URL segment. Lowercase letters, numbers, and hyphens only; changes may create redirects.
   */
  slug: string;
  subtitle?: string | null;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  welcome?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  courses?:
    | {
        section: 'bites' | 'starter' | 'fish' | 'meat' | 'main' | 'vegetarian-main' | 'sides' | 'dessert' | 'drinks';
        label?: string | null;
        items?: (number | MenuItem)[] | null;
        editorialNote?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Public wording only after recipe and service practice verification.
   */
  dietaryNotes?: string | null;
  featuredImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  availability: 'on-request' | 'seasonal' | 'unavailable';
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * A locale is public only after its copy and required media have been reviewed. Publishing alone is not sufficient.
   */
  localeReadiness?: {
    en?: boolean | null;
    fr?: boolean | null;
  };
  /**
   * Optional search and sharing overrides. Empty fields use approved site defaults.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Dishes and drinks. Dietary and allergen data must be explicitly verified.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items".
 */
export interface MenuItem {
  id: number;
  seedKey?: string | null;
  name: string;
  /**
   * URL segment. Lowercase letters, numbers, and hyphens only; changes may create redirects.
   */
  slug: string;
  category: number | MenuCategory;
  culinaryLevel: 'classic' | 'signature' | 'chef-creation';
  composition?:
    | {
        component: string;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  featuredImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  /**
   * Do not infer these values. Confirm recipes and cross-contamination policy first.
   */
  dietary?: {
    verifiedLabels?: ('gluten-free' | 'dairy-free' | 'nut-free' | 'halal' | 'vegetarian' | 'vegan')[] | null;
    allergens?:
      | (
          | 'celery'
          | 'crustaceans'
          | 'eggs'
          | 'fish'
          | 'gluten'
          | 'milk'
          | 'mustard'
          | 'nuts'
          | 'peanuts'
          | 'sesame'
          | 'shellfish'
          | 'soy'
        )[]
      | null;
    containsPork?: boolean | null;
    vegetarian?: boolean | null;
    vegan?: boolean | null;
    /**
     * Internal evidence/source for dietary and allergen labels.
     */
    verificationNote?: string | null;
  };
  spiceLevel?: ('mild' | 'medium' | 'hot') | null;
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * A locale is public only after its copy and required media have been reviewed. Publishing alone is not sufficient.
   */
  localeReadiness?: {
    en?: boolean | null;
    fr?: boolean | null;
  };
  /**
   * Optional search and sharing overrides. Empty fields use approved site defaults.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Editorial groupings and filter keys for individual menu items.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories".
 */
export interface MenuCategory {
  id: number;
  seedKey?: string | null;
  name: string;
  /**
   * URL segment. Lowercase letters, numbers, and hyphens only; changes may create redirects.
   */
  slug: string;
  family:
    | 'cocktail-classics'
    | 'meste-signature-cocktails'
    | 'chef-cocktail-creations'
    | 'starters'
    | 'heritage-african-roots'
    | 'fish-seafood'
    | 'poultry'
    | 'meat'
    | 'vegetable-table'
    | 'sides'
    | 'desserts';
  description?: string | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * A locale is public only after its copy and required media have been reviewed. Publishing alone is not sufficient.
   */
  localeReadiness?: {
    en?: boolean | null;
    fr?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Display-approved client work only. Permission is required independently of publish status.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "references".
 */
export interface Reference {
  id: number;
  clientName: string;
  logo?: (number | null) | Media;
  eventType?: string | null;
  guestCount?: number | null;
  shortDescription?: string | null;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photos?: (number | Media)[] | null;
  /**
   * Enable only with recorded client permission.
   */
  permissionToDisplay?: boolean | null;
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * A locale is public only after its copy and required media have been reviewed. Publishing alone is not sufficient.
   */
  localeReadiness?: {
    en?: boolean | null;
    fr?: boolean | null;
  };
  /**
   * Optional search and sharing overrides. Empty fields use approved site defaults.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Mama Emma Fresh range. Organic, nutrition, and legal claims require approval.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fresh-products".
 */
export interface FreshProduct {
  id: number;
  seedKey?: string | null;
  name: string;
  /**
   * URL segment. Lowercase letters, numbers, and hyphens only; changes may create redirects.
   */
  slug: string;
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  ingredients?:
    | {
        ingredient: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Use only official approved can photography or artwork.
   */
  canImage?: (number | null) | Media;
  accentColor:
    'pineapple-gold' | 'bissap-burgundy' | 'ginger-amber' | 'beetroot-ruby' | 'orange-citrus' | 'watermelon-coral';
  /**
   * Add only package sizes currently confirmed by the business.
   */
  availableSizes?:
    | {
        size: string;
        id?: string | null;
      }[]
    | null;
  availability: 'available' | 'seasonal' | 'unavailable' | 'to-confirm';
  /**
   * Internal placeholder only; not a verified nutrition claim.
   */
  nutritionPlaceholder?: string | null;
  /**
   * Internal placeholder pending approved product/legal wording.
   */
  legalPlaceholder?: string | null;
  gallery?: (number | Media)[] | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * A locale is public only after its copy and required media have been reviewed. Publishing alone is not sufficient.
   */
  localeReadiness?: {
    en?: boolean | null;
    fr?: boolean | null;
  };
  /**
   * Optional search and sharing overrides. Empty fields use approved site defaults.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Real testimonials only. Never publish without explicit display permission.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  role?: string | null;
  company?: string | null;
  quote: string;
  photo?: (number | null) | Media;
  /**
   * Enable only with recorded permission from the quoted person.
   */
  permissionToDisplay?: boolean | null;
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * A locale is public only after its copy and required media have been reviewed. Publishing alone is not sufficient.
   */
  localeReadiness?: {
    en?: boolean | null;
    fr?: boolean | null;
  };
  /**
   * Optional search and sharing overrides. Empty fields use approved site defaults.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Journal capability remains absent from navigation until real content is published.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts".
 */
export interface JournalPost {
  id: number;
  title: string;
  /**
   * URL segment. Lowercase letters, numbers, and hyphens only; changes may create redirects.
   */
  slug: string;
  excerpt: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  authorName?: string | null;
  publishedAt?: string | null;
  featuredImage?: (number | null) | Media;
  categories?: ('heritage' | 'hospitality' | 'menus' | 'fresh' | 'experience' | 'behind-the-scenes')[] | null;
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * A locale is public only after its copy and required media have been reviewed. Publishing alone is not sufficient.
   */
  localeReadiness?: {
    en?: boolean | null;
    fr?: boolean | null;
  };
  /**
   * Optional search and sharing overrides. Empty fields use approved site defaults.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Redirect registry created when published localized slugs change.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  fromPath: string;
  toPath: string;
  permanent: boolean;
  sourceCollection: string;
  sourceDocumentID: string;
  locale: 'en' | 'fr';
  updatedAt: string;
  createdAt: string;
}
/**
 * Private enquiries. Public submission is added through a validated server service in Phase 6.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  status: 'new' | 'contacted' | 'proposal-sent' | 'won' | 'lost';
  name: string;
  company?: string | null;
  email: string;
  phone: string;
  eventType?: string | null;
  eventDate?: string | null;
  location?: string | null;
  guestCount?: number | null;
  receptionFormat?: (number | null) | ReceptionFormat;
  services?: (number | Service)[] | null;
  menuPreferences?: string | null;
  dietaryRequirements?: string | null;
  allergens?: string | null;
  budget?: string | null;
  notes?: string | null;
  locale: 'en' | 'fr';
  sourcePage: string;
  consent: {
    accepted: boolean;
    version: string;
    acceptedAt: string;
  };
  delivery: {
    status: 'not-attempted' | 'queued' | 'sent' | 'failed';
    lastAttemptAt?: string | null;
    failureCode?: string | null;
  };
  /**
   * Private operational notes. Never returned to public clients.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Private Experience interest list. Public submission is implemented in Phase 6.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-interest".
 */
export interface ExperienceInterest {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  locale: 'en' | 'fr';
  sourcePage: string;
  marketingConsent: boolean;
  consentVersion: string;
  consentRecordedAt: string;
  deliveryStatus: 'not-attempted' | 'queued' | 'sent' | 'failed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'reception-formats';
        value: number | ReceptionFormat;
      } | null)
    | ({
        relationTo: 'menu-categories';
        value: number | MenuCategory;
      } | null)
    | ({
        relationTo: 'menu-items';
        value: number | MenuItem;
      } | null)
    | ({
        relationTo: 'signature-menus';
        value: number | SignatureMenu;
      } | null)
    | ({
        relationTo: 'fresh-products';
        value: number | FreshProduct;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'references';
        value: number | Reference;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'journal-posts';
        value: number | JournalPost;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'experience-interest';
        value: number | ExperienceInterest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  category?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  seedKey?: T;
  title?: T;
  slug?: T;
  pageKind?: T;
  editorial?:
    | T
    | {
        intro?:
          | T
          | {
              eyebrow?: T;
              headingLead?: T;
              headingAccent?: T;
              lede?: T;
            };
        closing?:
          | T
          | {
              heading?: T;
              body?: T;
              action?:
                | T
                | {
                    label?: T;
                    route?: T;
                  };
            };
      };
  aboutStory?:
    | T
    | {
        introImage?: T;
        eyebrow?: T;
        heading?: T;
        headingAccent?: T;
        chapters?:
          | T
          | {
              label?: T;
              title?: T;
              body?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              list?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              image?: T;
              id?: T;
            };
        pullQuote?:
          | T
          | {
              text?: T;
              attribution?: T;
            };
      };
  contactChannels?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              subline?: T;
              image?: T;
              alignment?: T;
              action?:
                | T
                | {
                    label?: T;
                    route?: T;
                  };
              id?: T;
              blockName?: T;
            };
        editorialTextImage?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              body?: T;
              image?: T;
              imageSide?: T;
              tone?: T;
              action?:
                | T
                | {
                    label?: T;
                    route?: T;
                  };
              id?: T;
              blockName?: T;
            };
        fullBleedImage?:
          | T
          | {
              image?: T;
              caption?: T;
              height?: T;
              id?: T;
              blockName?: T;
            };
        manifesto?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              statements?:
                | T
                | {
                    statement?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        serviceShowcase?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              items?: T;
              layout?: T;
              tone?: T;
              action?:
                | T
                | {
                    label?: T;
                    route?: T;
                  };
              id?: T;
              blockName?: T;
            };
        menuShowcase?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              items?: T;
              layout?: T;
              tone?: T;
              action?:
                | T
                | {
                    label?: T;
                    route?: T;
                  };
              id?: T;
              blockName?: T;
            };
        signatureDishes?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              items?: T;
              layout?: T;
              tone?: T;
              action?:
                | T
                | {
                    label?: T;
                    route?: T;
                  };
              id?: T;
              blockName?: T;
            };
        freshProducts?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              items?: T;
              layout?: T;
              tone?: T;
              action?:
                | T
                | {
                    label?: T;
                    route?: T;
                  };
              id?: T;
              blockName?: T;
            };
        galleryPreview?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              items?: T;
              layout?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        references?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              references?: T;
              presentation?: T;
              id?: T;
              blockName?: T;
            };
        process?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        mamaEmmaExperienceTeaser?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              description?: T;
              disclaimer?: T;
              image?: T;
              action?:
                | T
                | {
                    label?: T;
                    route?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              tone?: T;
              action?:
                | T
                | {
                    label?: T;
                    route?: T;
                  };
              id?: T;
              blockName?: T;
            };
        editorialSplit?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              left?: T;
              right?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        storyChapter?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              chapterKey?: T;
              body?: T;
              image?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
      };
  localeReadiness?:
    | T
    | {
        en?: T;
        fr?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  seedKey?: T;
  title?: T;
  slug?: T;
  category?: T;
  positioning?: T;
  story?: T;
  formats?: T;
  menus?: T;
  gallery?: T;
  references?: T;
  cta?:
    | T
    | {
        label?: T;
        route?: T;
      };
  sortOrder?: T;
  localeReadiness?:
    | T
    | {
        en?: T;
        fr?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reception-formats_select".
 */
export interface ReceptionFormatsSelect<T extends boolean = true> {
  seedKey?: T;
  name?: T;
  slug?: T;
  description?: T;
  recommendedEventTypes?:
    | T
    | {
        eventType?: T;
        id?: T;
      };
  verifiedGuestRange?:
    | T
    | {
        minimum?: T;
        maximum?: T;
      };
  gallery?: T;
  relatedMenus?: T;
  cta?:
    | T
    | {
        label?: T;
        route?: T;
      };
  sortOrder?: T;
  localeReadiness?:
    | T
    | {
        en?: T;
        fr?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories_select".
 */
export interface MenuCategoriesSelect<T extends boolean = true> {
  seedKey?: T;
  name?: T;
  slug?: T;
  family?: T;
  description?: T;
  sortOrder?: T;
  localeReadiness?:
    | T
    | {
        en?: T;
        fr?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items_select".
 */
export interface MenuItemsSelect<T extends boolean = true> {
  seedKey?: T;
  name?: T;
  slug?: T;
  category?: T;
  culinaryLevel?: T;
  composition?:
    | T
    | {
        component?: T;
        id?: T;
      };
  description?: T;
  featuredImage?: T;
  gallery?: T;
  dietary?:
    | T
    | {
        verifiedLabels?: T;
        allergens?: T;
        containsPork?: T;
        vegetarian?: T;
        vegan?: T;
        verificationNote?: T;
      };
  spiceLevel?: T;
  featured?: T;
  sortOrder?: T;
  localeReadiness?:
    | T
    | {
        en?: T;
        fr?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signature-menus_select".
 */
export interface SignatureMenusSelect<T extends boolean = true> {
  seedKey?: T;
  title?: T;
  slug?: T;
  subtitle?: T;
  intro?: T;
  welcome?: T;
  courses?:
    | T
    | {
        section?: T;
        label?: T;
        items?: T;
        editorialNote?: T;
        id?: T;
      };
  dietaryNotes?: T;
  featuredImage?: T;
  gallery?: T;
  availability?: T;
  sortOrder?: T;
  localeReadiness?:
    | T
    | {
        en?: T;
        fr?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fresh-products_select".
 */
export interface FreshProductsSelect<T extends boolean = true> {
  seedKey?: T;
  name?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  ingredients?:
    | T
    | {
        ingredient?: T;
        id?: T;
      };
  canImage?: T;
  accentColor?: T;
  availableSizes?:
    | T
    | {
        size?: T;
        id?: T;
      };
  availability?: T;
  nutritionPlaceholder?: T;
  legalPlaceholder?: T;
  gallery?: T;
  sortOrder?: T;
  localeReadiness?:
    | T
    | {
        en?: T;
        fr?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  seedKey?: T;
  title?: T;
  slug?: T;
  eventStatus?: T;
  theme?: T;
  shortDescription?: T;
  story?: T;
  schedule?:
    | T
    | {
        date?: T;
        venue?: T;
        capacity?: T;
        price?: T;
        currency?: T;
      };
  menu?: T;
  entertainment?: T;
  dressCode?: T;
  featuredImage?: T;
  gallery?: T;
  registration?:
    | T
    | {
        mode?: T;
        externalURL?: T;
      };
  sortOrder?: T;
  localeReadiness?:
    | T
    | {
        en?: T;
        fr?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "references_select".
 */
export interface ReferencesSelect<T extends boolean = true> {
  clientName?: T;
  logo?: T;
  eventType?: T;
  guestCount?: T;
  shortDescription?: T;
  fullDescription?: T;
  photos?: T;
  permissionToDisplay?: T;
  featured?: T;
  sortOrder?: T;
  localeReadiness?:
    | T
    | {
        en?: T;
        fr?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  company?: T;
  quote?: T;
  photo?: T;
  permissionToDisplay?: T;
  featured?: T;
  sortOrder?: T;
  localeReadiness?:
    | T
    | {
        en?: T;
        fr?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  image?: T;
  alt?: T;
  caption?: T;
  category?: T;
  event?: T;
  service?: T;
  sortOrder?: T;
  localeReadiness?:
    | T
    | {
        en?: T;
        fr?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts_select".
 */
export interface JournalPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  authorName?: T;
  publishedAt?: T;
  featuredImage?: T;
  categories?: T;
  featured?: T;
  sortOrder?: T;
  localeReadiness?:
    | T
    | {
        en?: T;
        fr?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  fromPath?: T;
  toPath?: T;
  permanent?: T;
  sourceCollection?: T;
  sourceDocumentID?: T;
  locale?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  status?: T;
  name?: T;
  company?: T;
  email?: T;
  phone?: T;
  eventType?: T;
  eventDate?: T;
  location?: T;
  guestCount?: T;
  receptionFormat?: T;
  services?: T;
  menuPreferences?: T;
  dietaryRequirements?: T;
  allergens?: T;
  budget?: T;
  notes?: T;
  locale?: T;
  sourcePage?: T;
  consent?:
    | T
    | {
        accepted?: T;
        version?: T;
        acceptedAt?: T;
      };
  delivery?:
    | T
    | {
        status?: T;
        lastAttemptAt?: T;
        failureCode?: T;
      };
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-interest_select".
 */
export interface ExperienceInterestSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  locale?: T;
  sourcePage?: T;
  marketingConsent?: T;
  consentVersion?: T;
  consentRecordedAt?: T;
  deliveryStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Safe public site identity and feature visibility. Secrets never belong here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  shortName: string;
  institutionalSignature: string;
  brandPhilosophy?: string | null;
  location: {
    city: string;
    country: string;
    timezone: string;
  };
  features?: {
    showJournal?: boolean | null;
    showEventsIndex?: boolean | null;
    showTestimonials?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Localized primary navigation using controlled application routes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navigation: {
    label: string;
    route: 'about' | 'experience' | 'fresh' | 'gallery' | 'menus' | 'quote' | 'services';
    id?: string | null;
  }[];
  primaryAction: {
    label: string;
    route: 'about' | 'experience' | 'fresh' | 'gallery' | 'menus' | 'quote' | 'services';
  };
  languageLabel: string;
  /**
   * A locale is public only after its copy and required media have been reviewed. Publishing alone is not sufficient.
   */
  localeReadiness?: {
    en?: boolean | null;
    fr?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Localized footer lines and controlled links. Empty contact values remain hidden.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  statement?: string | null;
  links?:
    | {
        label: string;
        route: 'about' | 'contact' | 'experience' | 'fresh' | 'gallery' | 'menus' | 'quote' | 'services';
        id?: string | null;
      }[]
    | null;
  /**
   * Add only after approved legal pages exist.
   */
  legalLinks?:
    | {
        label: string;
        path: string;
        id?: string | null;
      }[]
    | null;
  copyrightLine?: string | null;
  /**
   * A locale is public only after its copy and required media have been reviewed. Publishing alone is not sufficient.
   */
  localeReadiness?: {
    en?: boolean | null;
    fr?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Constrained homepage composition. Final rendering and visual validation belong to Phase 4.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  internalTitle: string;
  layout?:
    | (
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            subline?: string | null;
            image: number | Media;
            alignment: 'left' | 'center';
            action?: {
              label?: string | null;
              route?:
                | ('about' | 'contact' | 'experience' | 'fresh' | 'gallery' | 'home' | 'menus' | 'quote' | 'services')
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            image: number | Media;
            imageSide: 'left' | 'right';
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            action?: {
              label?: string | null;
              route?:
                | ('about' | 'contact' | 'experience' | 'fresh' | 'gallery' | 'home' | 'menus' | 'quote' | 'services')
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'editorialTextImage';
          }
        | {
            image: number | Media;
            caption?: string | null;
            height: 'cinematic' | 'viewport' | 'compact';
            id?: string | null;
            blockName?: string | null;
            blockType: 'fullBleedImage';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            statements: {
              statement: string;
              id?: string | null;
            }[];
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            id?: string | null;
            blockName?: string | null;
            blockType: 'manifesto';
          }
        | {
            quote: string;
            attribution?: string | null;
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            items?: (number | Service)[] | null;
            layout: 'editorial' | 'immersive' | 'compact';
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            action?: {
              label?: string | null;
              route?:
                | ('about' | 'contact' | 'experience' | 'fresh' | 'gallery' | 'home' | 'menus' | 'quote' | 'services')
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'serviceShowcase';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            items?: (number | SignatureMenu)[] | null;
            layout: 'editorial' | 'immersive' | 'compact';
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            action?: {
              label?: string | null;
              route?:
                | ('about' | 'contact' | 'experience' | 'fresh' | 'gallery' | 'home' | 'menus' | 'quote' | 'services')
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'menuShowcase';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            items?: (number | MenuItem)[] | null;
            layout: 'editorial' | 'immersive' | 'compact';
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            action?: {
              label?: string | null;
              route?:
                | ('about' | 'contact' | 'experience' | 'fresh' | 'gallery' | 'home' | 'menus' | 'quote' | 'services')
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'signatureDishes';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            items?: (number | FreshProduct)[] | null;
            layout: 'editorial' | 'immersive' | 'compact';
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            action?: {
              label?: string | null;
              route?:
                | ('about' | 'contact' | 'experience' | 'fresh' | 'gallery' | 'home' | 'menus' | 'quote' | 'services')
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'freshProducts';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            items?: (number | Gallery)[] | null;
            layout: 'editorial-grid' | 'filmstrip';
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            id?: string | null;
            blockName?: string | null;
            blockType: 'galleryPreview';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            references?: (number | Reference)[] | null;
            presentation: 'editorial' | 'quiet-list';
            id?: string | null;
            blockName?: string | null;
            blockType: 'references';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            steps: {
              title: string;
              description?: string | null;
              id?: string | null;
            }[];
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            id?: string | null;
            blockName?: string | null;
            blockType: 'process';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            description: string;
            disclaimer: string;
            image?: (number | null) | Media;
            action?: {
              label?: string | null;
              route?:
                | ('about' | 'contact' | 'experience' | 'fresh' | 'gallery' | 'home' | 'menus' | 'quote' | 'services')
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'mamaEmmaExperienceTeaser';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            action?: {
              label?: string | null;
              route?:
                | ('about' | 'contact' | 'experience' | 'fresh' | 'gallery' | 'home' | 'menus' | 'quote' | 'services')
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            left: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            right: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            tone: 'ivory' | 'forest' | 'burgundy' | 'charcoal';
            id?: string | null;
            blockName?: string | null;
            blockType: 'editorialSplit';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Preserve a logical heading outline; this is not a visual size control.
             */
            headingLevel: 'h2' | 'h3';
            chapterKey: 'congo' | 'maya-maya' | 'senegal' | 'professional-hospitality' | 'ghana' | 'meste-today';
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            image?: (number | null) | Media;
            layout: 'image-left' | 'image-right' | 'text-only';
            id?: string | null;
            blockName?: string | null;
            blockType: 'storyChapter';
          }
      )[]
    | null;
  featuredServices?: (number | Service)[] | null;
  featuredDishes?: (number | MenuItem)[] | null;
  featuredFreshProducts?: (number | FreshProduct)[] | null;
  /**
   * A locale is public only after its copy and required media have been reviewed. Publishing alone is not sufficient.
   */
  localeReadiness?: {
    en?: boolean | null;
    fr?: boolean | null;
  };
  /**
   * Optional search and sharing overrides. Empty fields use approved site defaults.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Optional threshold shown over the homepage on first arrival. Disabled by default. It never replaces the homepage: the address stays the same and search engines always receive the homepage itself.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entry-screen".
 */
export interface EntryScreen {
  id: number;
  /**
   * When off, visitors land directly on the homepage. When on, they see this threshold once per browsing session.
   */
  enabled?: boolean | null;
  /**
   * Small line above the headline. Leave empty to use the approved default.
   */
  eyebrow?: string | null;
  /**
   * The headline. Leave empty to use the approved default.
   */
  heading?: string | null;
  /**
   * One or two sentences. Leave empty to use the approved default.
   */
  body?: string | null;
  /**
   * Label of the button that opens the site.
   */
  ctaLabel?: string | null;
  /**
   * A locale is public only after its copy and required media have been reviewed. Publishing alone is not sufficient.
   */
  localeReadiness?: {
    en?: boolean | null;
    fr?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Verified public contact details. Empty values are never rendered.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings".
 */
export interface ContactSetting {
  id: number;
  /**
   * Stored as supplied until international format is confirmed.
   */
  phone?: string | null;
  whatsAppNumber?: string | null;
  whatsAppMessage?: string | null;
  publicEmail?: string | null;
  address?: {
    street?: string | null;
    locality?: string | null;
    region?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  serviceArea?: string | null;
  hours?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Legal wording shown beside the quote form consent checkbox, and the version recorded with every submission. The quote page is not published until both are filled.
   */
  quoteConsent?: {
    /**
     * Shown next to the checkbox. Supplied by MESTE, never drafted here.
     */
    statement?: string | null;
    /**
     * Stored with each lead so a change of wording stays auditable, e.g. 2026-08-v1.
     */
    version?: string | null;
  };
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'linkedin' | 'tiktok' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Search defaults and truthful organization metadata. Do not add unverified claims.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings".
 */
export interface SeoSetting {
  id: number;
  titleTemplate?: string | null;
  defaultDescription?: string | null;
  defaultSocialImage?: (number | null) | Media;
  organization?: {
    legalName?: string | null;
    publicName?: string | null;
    description?: string | null;
    logo?: (number | null) | Media;
  };
  robots?: {
    allowIndexing?: boolean | null;
    allowFollowing?: boolean | null;
  };
  /**
   * Administrator-only verification values; these are not application secrets.
   */
  verification?: {
    google?: string | null;
    bing?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  shortName?: T;
  institutionalSignature?: T;
  brandPhilosophy?: T;
  location?:
    | T
    | {
        city?: T;
        country?: T;
        timezone?: T;
      };
  features?:
    | T
    | {
        showJournal?: T;
        showEventsIndex?: T;
        showTestimonials?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navigation?:
    | T
    | {
        label?: T;
        route?: T;
        id?: T;
      };
  primaryAction?:
    | T
    | {
        label?: T;
        route?: T;
      };
  languageLabel?: T;
  localeReadiness?:
    | T
    | {
        en?: T;
        fr?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  statement?: T;
  links?:
    | T
    | {
        label?: T;
        route?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        path?: T;
        id?: T;
      };
  copyrightLine?: T;
  localeReadiness?:
    | T
    | {
        en?: T;
        fr?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  internalTitle?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              subline?: T;
              image?: T;
              alignment?: T;
              action?:
                | T
                | {
                    label?: T;
                    route?: T;
                  };
              id?: T;
              blockName?: T;
            };
        editorialTextImage?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              body?: T;
              image?: T;
              imageSide?: T;
              tone?: T;
              action?:
                | T
                | {
                    label?: T;
                    route?: T;
                  };
              id?: T;
              blockName?: T;
            };
        fullBleedImage?:
          | T
          | {
              image?: T;
              caption?: T;
              height?: T;
              id?: T;
              blockName?: T;
            };
        manifesto?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              statements?:
                | T
                | {
                    statement?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        serviceShowcase?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              items?: T;
              layout?: T;
              tone?: T;
              action?:
                | T
                | {
                    label?: T;
                    route?: T;
                  };
              id?: T;
              blockName?: T;
            };
        menuShowcase?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              items?: T;
              layout?: T;
              tone?: T;
              action?:
                | T
                | {
                    label?: T;
                    route?: T;
                  };
              id?: T;
              blockName?: T;
            };
        signatureDishes?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              items?: T;
              layout?: T;
              tone?: T;
              action?:
                | T
                | {
                    label?: T;
                    route?: T;
                  };
              id?: T;
              blockName?: T;
            };
        freshProducts?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              items?: T;
              layout?: T;
              tone?: T;
              action?:
                | T
                | {
                    label?: T;
                    route?: T;
                  };
              id?: T;
              blockName?: T;
            };
        galleryPreview?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              items?: T;
              layout?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        references?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              references?: T;
              presentation?: T;
              id?: T;
              blockName?: T;
            };
        process?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        mamaEmmaExperienceTeaser?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              description?: T;
              disclaimer?: T;
              image?: T;
              action?:
                | T
                | {
                    label?: T;
                    route?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              tone?: T;
              action?:
                | T
                | {
                    label?: T;
                    route?: T;
                  };
              id?: T;
              blockName?: T;
            };
        editorialSplit?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              left?: T;
              right?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        storyChapter?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingLevel?: T;
              chapterKey?: T;
              body?: T;
              image?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
      };
  featuredServices?: T;
  featuredDishes?: T;
  featuredFreshProducts?: T;
  localeReadiness?:
    | T
    | {
        en?: T;
        fr?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entry-screen_select".
 */
export interface EntryScreenSelect<T extends boolean = true> {
  enabled?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  ctaLabel?: T;
  localeReadiness?:
    | T
    | {
        en?: T;
        fr?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings_select".
 */
export interface ContactSettingsSelect<T extends boolean = true> {
  phone?: T;
  whatsAppNumber?: T;
  whatsAppMessage?: T;
  publicEmail?: T;
  address?:
    | T
    | {
        street?: T;
        locality?: T;
        region?: T;
        postalCode?: T;
        country?: T;
      };
  serviceArea?: T;
  hours?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  quoteConsent?:
    | T
    | {
        statement?: T;
        version?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings_select".
 */
export interface SeoSettingsSelect<T extends boolean = true> {
  titleTemplate?: T;
  defaultDescription?: T;
  defaultSocialImage?: T;
  organization?:
    | T
    | {
        legalName?: T;
        publicName?: T;
        description?: T;
        logo?: T;
      };
  robots?:
    | T
    | {
        allowIndexing?: T;
        allowFollowing?: T;
      };
  verification?:
    | T
    | {
        google?: T;
        bing?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null)
      | ({
          relationTo: 'reception-formats';
          value: number | ReceptionFormat;
        } | null)
      | ({
          relationTo: 'menu-categories';
          value: number | MenuCategory;
        } | null)
      | ({
          relationTo: 'menu-items';
          value: number | MenuItem;
        } | null)
      | ({
          relationTo: 'signature-menus';
          value: number | SignatureMenu;
        } | null)
      | ({
          relationTo: 'fresh-products';
          value: number | FreshProduct;
        } | null)
      | ({
          relationTo: 'events';
          value: number | Event;
        } | null)
      | ({
          relationTo: 'references';
          value: number | Reference;
        } | null)
      | ({
          relationTo: 'testimonials';
          value: number | Testimonial;
        } | null)
      | ({
          relationTo: 'gallery';
          value: number | Gallery;
        } | null)
      | ({
          relationTo: 'journal-posts';
          value: number | JournalPost;
        } | null);
    global?:
      | ('site-settings' | 'header' | 'footer' | 'home-page' | 'entry-screen' | 'contact-settings' | 'seo-settings')
      | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}